# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fba742179e6b261fc83818479cd5656140364a9f8ba565f6b41ecfeaa0edc38d590f34d6060885c90ec3c7135adcc46470bf17157a51772e6f0ed95c53e847b9

test:
  secret_key_base: 3dd9132b7e55e43d929a2a4210fc15b7c86bc505a7777afde971a4e14da97fda1589b4284a7d8ddb3a63b985da41b8445d66ae4c5b660b48e6968593266c37f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
